# -*- coding: utf-8 -*-
"""laco while e break.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uK5hTt-kAU26MSoW6WfCCbyPYQeM68K2
"""

while True:
  print('Voce está no primeiro laço \n')
  opcao1 = input('Voce deseja sair dele?, digite sim para isso\n')
  if opcao1 == 'sim':
   break
print('Voce saiu do primeiro laço!\n' )

while True:
  print('Agora voce está no segundo laço \n')
  opcao2 = input('Voce deseja sair do segundo laço?, digite sim para isso\n')
  if opcao2 == 'sim':
    break
print('Show, agora você saiu do segundo laço, até mais!')